### ISSUE TITLE
getting started has to be update

### ISSUE THREAD

**Issue by xfxpositions** [r4gus/uuid-zig#6]
Hi, i'm trying to install the library for 3 hours (literally, yes)

I already knew that the zig's build system and package management is sucks.

`exe.addPackagePath("uuid-zig", "path/to/uuid-zig/src/main.zig");`
add.PackagePath function is no longer in the latest release (0.12.0).

So the getting started part needs to update

```ts
    exe.root_module.addImport("uuid", uuid.module("uuid"));
    exe.linkLibrary(uuid.artifact("uuid-zig"));
    b.installArtifact(lib);
```
this is my build.zig

```ts
   .dependencies = .{ .uuid = .{
        .url = "https://github.com/r4gus/uuid-zig/archive/refs/tags/0.2.0.tar.gz",
        .hash = "12205faefc87ea2d9182f7e28f2e8effeae3b070727e68cfb7330ce5d78bbcd90dfc",
    } },
```

and this is my build.zig.zon
But currently i'm getting
```ts
src/utils/uuid.zig:1:22: error: no module named 'uuid' available within module root
const uuid = @import("uuid");
```

I'm still figuring out how could import the library, They changed the whole thing.

**Comment by r4gus** [comment]
Try something like:

```zig
const uuid_dep = b.dependency("uuid", .{
        .target = target,
        .optimize = optimize,
    });
    const uuid_module = uuid_dep.module("uuid");

    const lib = b.addStaticLibrary(.{
        .name = "your-lib",
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .optimize = optimize,
    });
    lib.root_module.addImport("uuid", uuid_module);
    b.installArtifact(lib);
```

**Comment by r4gus** [comment]
here is an example project
[uuid-example.tar.gz](https://github.com/r4gus/uuid-zig/files/15408159/uuid-example.tar.gz)
